# Numpy assignment

# 1. Create a 3x3x3 array with random values

In [1]:
import numpy as np

In [2]:
np.random.randint(0,50,size = (3,3,3))

array([[[27,  7, 38],
        [ 7, 29,  5],
        [20, 44, 42]],

       [[48, 34, 10],
        [15, 17, 25],
        [34,  0,  8]],

       [[13, 44, 33],
        [39, 48,  2],
        [20, 35, 40]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
a=np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
a[1,0] = 1
a[2,1] = 2
a[3,2] = 3
a[4,3] = 4
a.astype(int)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [5]:
arr = np.zeros((8,8)).astype(int)
arr

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
for i in range(0,8,2):
    for j in range(0,8,2):
        arr[i,j] = 1
        
for i in range(1,8,2):
    for j in range(1,8,2):
        arr[i,j] = 1
        
print(arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 4. Normalize a 5x5 random matrix

In [7]:
arry = np.arange(0,25).reshape(5,5)
norm = np.linalg.norm(arry)
normal_arry = arry/norm
normal_arry

array([[0.        , 0.01428571, 0.02857143, 0.04285714, 0.05714286],
       [0.07142857, 0.08571429, 0.1       , 0.11428571, 0.12857143],
       [0.14285714, 0.15714286, 0.17142857, 0.18571429, 0.2       ],
       [0.21428571, 0.22857143, 0.24285714, 0.25714286, 0.27142857],
       [0.28571429, 0.3       , 0.31428571, 0.32857143, 0.34285714]])

# 5. How to find common values between two arrays?

In [10]:
arry1 = np.array([2,3,4,5,7,6])
arry2 = np.array([0,3,1,8,9,6,7,5,8])
np.intersect1d(arry1, arry2)

array([3, 5, 6, 7])

# 6.How to get the dates of yesterday, today and tomorrow?

In [11]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D') 
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print(f"Yesterday: {yesterday}\nToday: {today}\nTomorrow: {tomorrow}")

Yesterday: 2020-07-26
Today: 2020-07-27
Tomorrow: 2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [21]:
A = np.random.randint(0,5, size=(2,2))
print(A)
B = np.random.randint(0,5, size=(2,2))
print(B)
np.allclose(A,B)

[[0 1]
 [2 0]]
[[2 2]
 [1 2]]


False

# 8.Create random vector of size 10 and replace the maximum value by 0


In [24]:
arr = np.random.random(20)
arr[np.where(arr==arr.max())] = 0
arr

array([0.00574393, 0.30807202, 0.2882817 , 0.96172574, 0.0567199 ,
       0.26877869, 0.70179148, 0.48156822, 0.        , 0.08083931,
       0.01730177, 0.67575155, 0.16091349, 0.5184689 , 0.61309255,
       0.37843713, 0.31108332, 0.10417283, 0.73535532, 0.87028175])

# 9. How to print all the values of an array?

In [29]:
array = np.array([10,20,30,40,50])
for index, ele in enumerate(array):
    print(f"{ele} is at index {index}")

10 is at index 0
20 is at index 1
30 is at index 2
40 is at index 3
50 is at index 4


# 10.Subtract the mean of each row of a matrix

In [28]:
arr = np.random.randint(5,30, size=(3,3))
arr - arr.mean(axis=1, keepdims=True).astype(int)

array([[  3,   3,  -5],
       [  8,   3, -11],
       [ -2,  10,  -8]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [30]:
arr1 = np.random.randint(10,50,5)
arr1

array([32, 20, 42, 31, 37])

In [31]:
b = [3,0,1,4,2]
arr = arr1[b]+1
arr

array([32, 33, 21, 38, 43])

# 12.How to get the diagonal of a dot product?

In [36]:
array = np.arange(16).reshape(4,4)
array1 = np.arange(40,56).reshape(4,4)
a_dot = array.dot(array1)
np.diag(a_dot)

array([ 296, 1054, 1844, 2666])

# 13.How to find the most frequent value in an array? 

In [38]:
from scipy.stats import mode
arr = np.array([40,20,56,78,94,34,56,78,23])
mode(arr)[0]

array([56])

# 14.How to get the n largest values of an array

In [39]:
arr

array([40, 20, 56, 78, 94, 34, 56, 78, 23])

In [41]:
arr.max()

94

# 15.How to create a record array from a regular array?

In [43]:
arr1 = np.array([(10,20,30), (44,54,64), (77,87,97)])
arr2 = np.core.records.fromarrays(arr1.T, names='a, b, c', formats= 'i8,i8,i8')
print(arr1)
print(arr2)

[[10 20 30]
 [44 54 64]
 [77 87 97]]
[(10, 20, 30) (44, 54, 64) (77, 87, 97)]
